# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dice_sim.ui'
##
## Created by: Qt User Interface Compiler version 6.0.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(548, 386)
        MainWindow.setMinimumSize(QSize(548, 386))
        MainWindow.setMaximumSize(QSize(548, 386))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 548, 386))
        self.tabWidget.setMinimumSize(QSize(548, 386))
        self.tabWidget.setMaximumSize(QSize(548, 386))
        self.tabWidget.setAutoFillBackground(False)
        self.single_tab = QWidget()
        self.single_tab.setObjectName(u"single_tab")
        self.label_atk_1 = QLabel(self.single_tab)
        self.label_atk_1.setObjectName(u"label_atk_1")
        self.label_atk_1.setGeometry(QRect(30, 10, 161, 51))
        font = QFont()
        font.setFamily(u"Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        self.label_atk_1.setFont(font)
        self.label_def_1 = QLabel(self.single_tab)
        self.label_def_1.setObjectName(u"label_def_1")
        self.label_def_1.setGeometry(QRect(30, 100, 161, 61))
        self.label_def_1.setFont(font)
        self.roll_btn = QPushButton(self.single_tab)
        self.roll_btn.setObjectName(u"roll_btn")
        self.roll_btn.setGeometry(QRect(30, 200, 141, 131))
        self.roll_btn.setFont(font)
        self.roll_btn.setAutoFillBackground(True)
        self.roll_btn.setAutoDefault(False)
        self.roll_btn.setFlat(False)
        self.line = QFrame(self.single_tab)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-13, 170, 571, 20))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.atk_button_container = QFrame(self.single_tab)
        self.atk_button_container.setObjectName(u"atk_button_container")
        self.atk_button_container.setGeometry(QRect(200, 6, 321, 61))
        self.atk_button_container.setFrameShape(QFrame.NoFrame)
        self.atk_button_container.setFrameShadow(QFrame.Plain)
        self.atk_btn_1 = QPushButton(self.atk_button_container)
        self.atk_btn_1.setObjectName(u"atk_btn_1")
        self.atk_btn_1.setGeometry(QRect(30, 10, 61, 41))
        self.atk_btn_1.setFont(font)
        self.atk_btn_1.setCheckable(False)
        self.atk_btn_1.setAutoExclusive(True)
        self.atk_btn_2 = QPushButton(self.atk_button_container)
        self.atk_btn_2.setObjectName(u"atk_btn_2")
        self.atk_btn_2.setGeometry(QRect(130, 10, 61, 41))
        self.atk_btn_2.setFont(font)
        self.atk_btn_2.setCheckable(False)
        self.atk_btn_2.setAutoExclusive(True)
        self.atk_btn_3 = QPushButton(self.atk_button_container)
        self.atk_btn_3.setObjectName(u"atk_btn_3")
        self.atk_btn_3.setGeometry(QRect(230, 10, 61, 41))
        self.atk_btn_3.setFont(font)
        self.atk_btn_3.setCheckable(False)
        self.atk_btn_3.setChecked(False)
        self.atk_btn_3.setAutoExclusive(True)
        self.def_button_container = QFrame(self.single_tab)
        self.def_button_container.setObjectName(u"def_button_container")
        self.def_button_container.setGeometry(QRect(200, 100, 221, 61))
        self.def_button_container.setFrameShape(QFrame.NoFrame)
        self.def_button_container.setFrameShadow(QFrame.Raised)
        self.def_btn_2 = QPushButton(self.def_button_container)
        self.def_btn_2.setObjectName(u"def_btn_2")
        self.def_btn_2.setGeometry(QRect(130, 10, 61, 41))
        self.def_btn_2.setFont(font)
        self.def_btn_2.setCheckable(False)
        self.def_btn_2.setChecked(False)
        self.def_btn_2.setAutoExclusive(True)
        self.def_btn_1 = QPushButton(self.def_button_container)
        self.def_btn_1.setObjectName(u"def_btn_1")
        self.def_btn_1.setGeometry(QRect(30, 10, 61, 41))
        self.def_btn_1.setFont(font)
        self.def_btn_1.setCheckable(False)
        self.def_btn_1.setAutoExclusive(True)
        self.atk_dice_label = QLabel(self.single_tab)
        self.atk_dice_label.setObjectName(u"atk_dice_label")
        self.atk_dice_label.setGeometry(QRect(190, 210, 51, 31))
        self.atk_dice_label.setFont(font)
        self.def_dice_label = QLabel(self.single_tab)
        self.def_dice_label.setObjectName(u"def_dice_label")
        self.def_dice_label.setGeometry(QRect(190, 290, 51, 31))
        self.def_dice_label.setFont(font)
        self.atk_roll_result = QLineEdit(self.single_tab)
        self.atk_roll_result.setObjectName(u"atk_roll_result")
        self.atk_roll_result.setGeometry(QRect(390, 210, 101, 31))
        self.atk_roll_result.setFont(font)
        self.atk_roll_result.setAlignment(Qt.AlignCenter)
        self.atk_roll_result.setReadOnly(True)
        self.atk_dice_num = QLineEdit(self.single_tab)
        self.atk_dice_num.setObjectName(u"atk_dice_num")
        self.atk_dice_num.setGeometry(QRect(250, 210, 31, 31))
        self.atk_dice_num.setFont(font)
        self.atk_dice_num.setCursorPosition(0)
        self.atk_dice_num.setAlignment(Qt.AlignCenter)
        self.atk_dice_num.setReadOnly(True)
        self.def_dice_num = QLineEdit(self.single_tab)
        self.def_dice_num.setObjectName(u"def_dice_num")
        self.def_dice_num.setGeometry(QRect(250, 290, 31, 31))
        self.def_dice_num.setFont(font)
        self.def_dice_num.setAlignment(Qt.AlignCenter)
        self.def_dice_num.setReadOnly(True)
        self.def_roll_result = QLineEdit(self.single_tab)
        self.def_roll_result.setObjectName(u"def_roll_result")
        self.def_roll_result.setGeometry(QRect(390, 290, 101, 31))
        self.def_roll_result.setFont(font)
        self.def_roll_result.setAlignment(Qt.AlignCenter)
        self.def_roll_result.setReadOnly(True)
        self.label = QLabel(self.single_tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(300, 210, 81, 31))
        self.label.setFont(font)
        self.label_2 = QLabel(self.single_tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(300, 290, 81, 31))
        self.label_2.setFont(font)
        self.tabWidget.addTab(self.single_tab, "")
        self.blitz_tab = QWidget()
        self.blitz_tab.setObjectName(u"blitz_tab")
        self.label_atk_2 = QLabel(self.blitz_tab)
        self.label_atk_2.setObjectName(u"label_atk_2")
        self.label_atk_2.setGeometry(QRect(30, 10, 281, 51))
        font1 = QFont()
        font1.setFamily(u"Segoe UI Black")
        font1.setPointSize(20)
        font1.setBold(True)
        self.label_atk_2.setFont(font1)
        self.label_atk_2.setFrameShape(QFrame.NoFrame)
        self.label_def_2 = QLabel(self.blitz_tab)
        self.label_def_2.setObjectName(u"label_def_2")
        self.label_def_2.setGeometry(QRect(30, 100, 281, 61))
        self.label_def_2.setFont(font1)
        self.line_2 = QFrame(self.blitz_tab)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(-10, 170, 571, 20))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.onslaught_btn = QPushButton(self.blitz_tab)
        self.onslaught_btn.setObjectName(u"onslaught_btn")
        self.onslaught_btn.setGeometry(QRect(30, 200, 141, 131))
        self.onslaught_btn.setFont(font)
        self.atk_onslaught_result = QLineEdit(self.blitz_tab)
        self.atk_onslaught_result.setObjectName(u"atk_onslaught_result")
        self.atk_onslaught_result.setGeometry(QRect(340, 210, 151, 41))
        self.atk_onslaught_result.setFont(font1)
        self.atk_onslaught_result.setMaxLength(9)
        self.atk_onslaught_result.setAlignment(Qt.AlignCenter)
        self.atk_onslaught_result.setReadOnly(True)
        self.def_onslaught_result = QLineEdit(self.blitz_tab)
        self.def_onslaught_result.setObjectName(u"def_onslaught_result")
        self.def_onslaught_result.setGeometry(QRect(340, 280, 151, 41))
        self.def_onslaught_result.setFont(font1)
        self.def_onslaught_result.setMaxLength(9)
        self.def_onslaught_result.setAlignment(Qt.AlignCenter)
        self.def_onslaught_result.setReadOnly(True)
        self.atk_army_total = QSpinBox(self.blitz_tab)
        self.atk_army_total.setObjectName(u"atk_army_total")
        self.atk_army_total.setGeometry(QRect(340, 15, 151, 41))
        self.atk_army_total.setFont(font1)
        self.atk_army_total.setReadOnly(False)
        self.atk_army_total.setAccelerated(True)
        self.atk_army_total.setMinimum(0)
        self.atk_army_total.setMaximum(999)
        self.atk_army_total.setValue(0)
        self.def_army_total = QSpinBox(self.blitz_tab)
        self.def_army_total.setObjectName(u"def_army_total")
        self.def_army_total.setGeometry(QRect(340, 110, 151, 41))
        self.def_army_total.setFont(font1)
        self.def_army_total.setFrame(True)
        self.def_army_total.setReadOnly(False)
        self.def_army_total.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.def_army_total.setAccelerated(True)
        self.def_army_total.setMinimum(0)
        self.def_army_total.setMaximum(999)
        self.def_army_total.setValue(0)
        self.label_3 = QLabel(self.blitz_tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(200, 210, 111, 41))
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.blitz_tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(200, 280, 111, 41))
        self.label_4.setFont(font1)
        self.tabWidget.addTab(self.blitz_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.roll_btn.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Risk Dice Roller", None))
        self.label_atk_1.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#aa0000;\">ATTACKER DICE</span></p></body></html>", None))
        self.label_def_1.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#00557f;\">DEFENDER DICE</span></p></body></html>", None))
        self.roll_btn.setText(QCoreApplication.translate("MainWindow", u"ROLL", None))
        self.atk_btn_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.atk_btn_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.atk_btn_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.def_btn_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.def_btn_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.atk_dice_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#aa0000;\">DICE</span></p></body></html>", None))
        self.def_dice_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#00557f;\">DICE</span></p></body></html>", None))
        self.atk_roll_result.setText("")
        self.atk_dice_num.setText("")
        self.def_roll_result.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#aa0000;\">RESULT</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#00557f;\">RESULT</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.single_tab), QCoreApplication.translate("MainWindow", u"SINGLE", None))
        self.label_atk_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#aa0000;\">ATTACKING ARMIES</span></p></body></html>", None))
        self.label_def_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#00557f;\">DEFENDING ARMIES</span></p></body></html>", None))
        self.onslaught_btn.setText(QCoreApplication.translate("MainWindow", u"ONSLAUGHT", None))
        self.atk_onslaught_result.setText("")
        self.def_onslaught_result.setText("")
        self.def_army_total.setSuffix("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#aa0000;\">RESULT</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#00557f;\">RESULT</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.blitz_tab), QCoreApplication.translate("MainWindow", u"ONSLAUGHT", None))
    # retranslateUi

